services:
  - type: web
    name: mytasks
    env: python
    buildCommand: |
      pip install -r Config/requirements.txt
      echo "from django.contrib.auth.models import User; User.objects.create_superuser('admin', 'admin@example.com', 'password123')" | python Config/manage.py shell
    startCommand: |
      python Config/manage.py migrate --noinput
      gunicorn Config.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: Config.settings
