services:
  - type: web
    name: mytasks
    env: python
    buildCommand: |
      pip install -r Config/requirements.txt
      echo "from django.contrib.auth.models import User; User.objects.create_superuser('admin', 'admin@example.com', 'password123')" | python manage.py shell
    startCommand: "python manage.py migrate && gunicorn MyTasks.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: MyTasks.settings
