# Generated by Django 5.2.4 on 2025-07-18 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyTasks', '0002_alter_task_options_task_parent_task_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
    ]
